import "dotenv/config"; // ไฟล์ตั้งค่าของ Prisma CLI: migrate, generate, validate และ studio จะอ่านไฟล์นี้ | ปกติไม่ต้องแก้บ่อย โดยไฟล์นี้ชี้ไป schema.prisma และอ่าน DATABASE_URL จาก .env | This file was generated by Prisma, and assumes you have installed the following: | npm install --save-dev prisma dotenv | โหลด DATABASE_URL จากไฟล์ .env ก่อน Prisma CLI อ่าน Config
import { defineConfig } from "prisma/config"; // defineConfig ช่วยตรวจรูปแบบ Config ของ Prisma

export default defineConfig({
  schema: "prisma/schema.prisma", // ระบุตำแหน่งไฟล์ Model/Enum ของ Database
  migrations: { // กำหนดโฟลเดอร์เก็บประวัติ Migration
    path: "prisma/migrations", // Prisma จะสร้างไฟล์ Migration ไว้ใน path นี้
  },
  datasource: { // ส่ง Connection URL จาก Environment ให้ Prisma CLI
    url: process.env["DATABASE_URL"], // Neon PostgreSQL connection string
  },
});
